# Generated by Django 4.2.5 on 2023-11-10 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=8, verbose_name='Тип доставки')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=7, verbose_name='Тип оплаты')),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='deliveryType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='orders.delivery', verbose_name='Тип доставки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='paymentType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='orders.payment', verbose_name='Тип оплаты'),
        ),
    ]
