# Generated by Django 4.2.5 on 2023-11-10 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_delivery_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='delivery',
            options={'verbose_name': 'Тип доставки', 'verbose_name_plural': 'Типы доставок'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': 'Вид платежа', 'verbose_name_plural': 'Виды платежей'},
        ),
    ]
