# Generated by Django 4.2.5 on 2023-11-10 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_delivery_options_alter_payment_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='freePrice',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Мин. цена для бесплатной доставки'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='tax',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Плата за доставку'),
        ),
    ]
