# Generated by Django 4.2.5 on 2023-10-30 14:02

from django.db import migrations, models
import django.db.models.deletion
import products.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tags', '0001_initial'),
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Цена')),
                ('count', models.SmallIntegerField(default=0, verbose_name='Количество')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.CharField(blank=True, max_length=50, null=True, verbose_name='Краткое описание')),
                ('fullDescription', models.CharField(blank=True, max_length=500, null=True, verbose_name='Полное описание')),
                ('freeDelivery', models.BooleanField(default=False, verbose_name='Бесплатная доставка')),
                ('images', models.ImageField(blank=True, null=True, upload_to=products.models.product_image_directory_path, verbose_name='Иозбражения')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.categories', verbose_name='Категория')),
                ('tags', models.ManyToManyField(to='tags.tags', verbose_name='Теги')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
    ]
