# Generated by Django 4.2.5 on 2023-10-30 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='product',
            name='fullDescription',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Полное описание'),
        ),
    ]
