# Generated by Django 4.2.5 on 2023-11-03 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_imageforproduct_remove_product_images_product_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageforproduct',
            name='name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='images',
        ),
        migrations.AddField(
            model_name='imageforproduct',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.product'),
            preserve_default=False,
        ),
    ]
