# Generated by Django 4.2.5 on 2023-11-13 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_product_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='dateFrom',
            field=models.DateField(blank=True, null=True, verbose_name='Начало акции'),
        ),
        migrations.AddField(
            model_name='product',
            name='dateTo',
            field=models.DateField(blank=True, null=True, verbose_name='Конец акции'),
        ),
        migrations.AddField(
            model_name='product',
            name='limitedEdition',
            field=models.BooleanField(default=False, verbose_name='Ограниченный тираж'),
        ),
        migrations.AddField(
            model_name='product',
            name='onSales',
            field=models.BooleanField(default=False, verbose_name='Участвует в акции'),
        ),
        migrations.AddField(
            model_name='product',
            name='purchases',
            field=models.SmallIntegerField(default=0, verbose_name='Количество покупок'),
        ),
        migrations.AddField(
            model_name='product',
            name='salePrice',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=8, null=True, verbose_name='Цена при акции'),
        ),
    ]
