# Generated by Django 4.2.5 on 2023-11-13 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_product_datefrom_product_dateto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='salePrice',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=8, null=True, verbose_name='Цена при акции'),
        ),
    ]
