# Generated by Django 4.2.5 on 2023-10-25 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.CharField(max_length=75, unique=True, verbose_name='Электронная почта'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(max_length=12, unique=True, verbose_name='Номер телефона'),
        ),
    ]
